# Generated by Django 2.1.5 on 2021-08-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diawe', '0006_auto_20210804_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTeam', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='nameU',
            field=models.ManyToManyField(to='diawe.UserN'),
        ),
        migrations.AddField(
            model_name='logpost',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diawe.Teams'),
            preserve_default=False,
        ),
    ]
