# Generated by Django 2.1.5 on 2021-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0006_auto_20210804_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/'),
        ),
    ]
