# Generated by Django 2.1.5 on 2021-08-05 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0007_auto_20210805_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usern',
            name='userd',
        ),
        migrations.AddField(
            model_name='teams',
            name='idT',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='nameTeam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teams',
            name='nameU',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserN',
        ),
    ]
