# Generated by Django 2.1.5 on 2021-08-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diawe', '0008_auto_20210805_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='teams',
            name='nameU',
        ),
        migrations.AddField(
            model_name='usern',
            name='idTe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diawe.Teams', to_field='idT'),
        ),
        migrations.AddField(
            model_name='usern',
            name='userN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
