# Generated by Django 2.1.5 on 2021-08-05 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diawe', '0009_auto_20210805_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usern',
            name='idTe',
        ),
        migrations.RemoveField(
            model_name='usern',
            name='userN',
        ),
        migrations.AddField(
            model_name='teams',
            name='nameU',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='UserN',
        ),
    ]
