# Generated by Django 2.1.5 on 2021-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0010_auto_20210805_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='nameU',
        ),
        migrations.AddField(
            model_name='teams',
            name='users',
            field=models.ManyToManyField(to='diawe.UserProfile'),
        ),
    ]
