# Generated by Django 2.1.5 on 2021-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0012_auto_20210806_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
