# Generated by Django 2.1.5 on 2021-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0015_auto_20210806_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
