# Generated by Django 2.1.5 on 2021-08-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0016_auto_20210806_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/'),
        ),
    ]
