# Generated by Django 2.1.5 on 2021-08-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0007_logpost_picture'),
        ('diawe', '0016_auto_20210806_0223'),
    ]

    operations = [
    ]
